import XCTest
import DocReader

/// Integration tests that run against real fixture files.
///
/// Fixtures are located in `Tests/DocReaderIntegrationTests/Fixtures/`.
/// They are generated by LibreOffice headless in CI (see `.github/workflows/ci.yml`).
/// To run locally, place fixture files in the Fixtures directory.
final class OOXMLParserIntegrationTests: XCTestCase {
    private var fixturesURL: URL {
        Bundle.module.resourceURL!.appendingPathComponent("Fixtures")
    }

    // MARK: - DOCX

    func testDocxPageCountBasic() async throws {
        let url = fixturesURL.appendingPathComponent("word_1page.docx")
        try XCTSkipUnless(FileManager.default.fileExists(atPath: url.path),
                          "Fixture word_1page.docx not found")

        let doc = try await DocReader.open(url: url)
        let count = try await doc.pageCount
        XCTAssertGreaterThanOrEqual(count, 1)
        XCTAssertLessThanOrEqual(count, 2, "Tolerance ±1")
    }

    func testDocxMultiPage() async throws {
        let url = fixturesURL.appendingPathComponent("word_10page.docx")
        try XCTSkipUnless(FileManager.default.fileExists(atPath: url.path),
                          "Fixture word_10page.docx not found")

        let doc = try await DocReader.open(url: url)
        let count = try await doc.pageCount
        XCTAssertGreaterThanOrEqual(count, 9, "Expected ~10 pages (±1 tolerance)")
        XCTAssertLessThanOrEqual(count, 11)
    }

    func testDocxPageSize() async throws {
        let url = fixturesURL.appendingPathComponent("word_1page.docx")
        try XCTSkipUnless(FileManager.default.fileExists(atPath: url.path),
                          "Fixture word_1page.docx not found")

        let doc = try await DocReader.open(url: url)
        let size = try await doc.pageSize(at: 0)
        XCTAssertGreaterThan(size.width, 0)
        XCTAssertGreaterThan(size.height, 0)
    }

    // MARK: - XLSX

    func testXlsxSheetCount() async throws {
        let url = fixturesURL.appendingPathComponent("excel_3sheet.xlsx")
        try XCTSkipUnless(FileManager.default.fileExists(atPath: url.path),
                          "Fixture excel_3sheet.xlsx not found")

        let doc = try await DocReader.open(url: url)
        let count = try await doc.pageCount
        XCTAssertGreaterThanOrEqual(count, 2)
        XCTAssertLessThanOrEqual(count, 4, "Tolerance ±1")
    }

    // MARK: - PPTX

    func testPptxSlideCount() async throws {
        let url = fixturesURL.appendingPathComponent("ppt_5slide.pptx")
        try XCTSkipUnless(FileManager.default.fileExists(atPath: url.path),
                          "Fixture ppt_5slide.pptx not found")

        let doc = try await DocReader.open(url: url)
        let count = try await doc.pageCount
        XCTAssertGreaterThanOrEqual(count, 4)
        XCTAssertLessThanOrEqual(count, 6, "Tolerance ±1")
    }

    func testPptxSlideSize() async throws {
        let url = fixturesURL.appendingPathComponent("ppt_5slide.pptx")
        try XCTSkipUnless(FileManager.default.fileExists(atPath: url.path),
                          "Fixture ppt_5slide.pptx not found")

        let doc = try await DocReader.open(url: url)
        let size = try await doc.pageSize(at: 0)
        // Widescreen: ~720×405 or standard ~720×540
        XCTAssertGreaterThan(size.width, 400)
        XCTAssertGreaterThan(size.height, 300)
    }

    // MARK: - Corrupted file

    func testCorruptedOOXMLThrows() async throws {
        let tempURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("corrupted.docx")
        defer { try? FileManager.default.removeItem(at: tempURL) }

        // Write a valid ZIP header but no Content_Types.xml
        let zipHeader: [UInt8] = [0x50, 0x4B, 0x03, 0x04]
        try Data(zipHeader).write(to: tempURL)

        let doc = try await DocReader.open(url: tempURL)
        do {
            _ = try await doc.pageCount
            XCTFail("Expected corruptedFile to be thrown")
        } catch DocReaderError.corruptedFile {
            // expected
        }
    }

    // MARK: - PDF export

    func testExportOnePage() async throws {
        let url = fixturesURL.appendingPathComponent("word_1page.docx")
        try XCTSkipUnless(FileManager.default.fileExists(atPath: url.path),
                          "Fixture word_1page.docx not found")

        let doc = try await DocReader.open(url: url)
        let pdf = try await doc.exportPDF(pages: 0...0)
        XCTAssertTrue(pdf.starts(with: [0x25, 0x50, 0x44, 0x46]), "Output must start with %PDF")
    }

    func testExportInvalidRangeThrows() async throws {
        let url = fixturesURL.appendingPathComponent("word_1page.docx")
        try XCTSkipUnless(FileManager.default.fileExists(atPath: url.path),
                          "Fixture word_1page.docx not found")

        let doc = try await DocReader.open(url: url)
        do {
            _ = try await doc.exportPDF(pages: 100...200)
            XCTFail("Expected pageOutOfRange")
        } catch DocReaderError.pageOutOfRange {
            // expected
        }
    }
}
